spring:
  profiles:
    active:
    - default
  application:
    name: Dev-Portal
  data:
    mongodb:
      database: mydb
      uri: mongodb://yanshu:root@localhost:27017/mydb

jwt:
  secret: javainuse

      
server:
  port: 8080
