#--- 
#security: 
#  oauth2:
##    resource:
##      filter-order: 3
#    client: 
#      client-id: first-client
#      client-secret: noonewilleverguess
#  spring.main.allow-bean-definition-overriding=true
spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      database: mydb
      uri: mongodb://yanshu:root@localhost:27017/mydb

jwt:
  secret: javainuse

#security.oauth2.client.client-id=first-client
#security.oauth2.client.client-secret=noonewilleverguess